server:
  port: 9501
zuul:
  prefix: /mldn-proxy
  ignored-services:
    "*"
  routes:
    uaa:
      path: /uaa/**
    microcloud-provider-dept: /dept/**
  add-proxy-headers: true
#  sensitive-headers: Cookie,Set-cookie
hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
eureka:
  client:
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: gateway-9501.com
    prefer-ip-address: true
info:
  app.name: mldn-microcloud
  company.name: www.macfu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: microcloud-zuul-gateway
security:
  oauth2:
    client:
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
      client-id: cmldn
      client-secret: cjava
    resource:
      user-info-uri: http://localhost:8080/user


