server:
  port: 8001
eureka:
  client:   # 客户端进行eureka注册的配置
    service-url:
    defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30      # 设置心跳的间隔时间(默认30)
    lease-expiration-duration-in-seconds: 90   # 如果现在超过了90秒的间隔(默认90s)
    instance-id: dept-8001.com              # 在信息列表时显示主机名称
    prefer-ip-address: true       # 访问的路径变为ip地址
info:
  app.name: mldn-microcloud
  company.name: www.mldn.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.macfu.po          # 定义所有操作类的别名所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml   # 所有的mapper文件
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver    # 配置mysql的驱动程序类
    url: jdbc:mysql://45.78.12.29:3306/macfu8001    # 数据库的连接地址
    username: root    # 用户名
    password: mysqladmin    # 密码
    dbcp2:    # 进行数据库连接池的配置
      min-idle: 5   # 数据库连接池的最小维持连接数
      initial-size: 5   # 初始化的连接数
      max-total: 5    # 最大的连接数
      max-wait-millis: 2000   # 等待连接获取时间超时时间
  application:
    name: microcloud-provider-dept
security:
  oauth2:
    resource:
      id: dept-service
      user-info-uri: http://localhost:8080/user
      prefer-token-info: false  # 必须在有token存在的情况下才可以获得资源项
