server:
  port: 80
logging:
  level:
    com.macfu.service: DEBUG
feign:
  hystrix:
    enable: true
  compression:
    request:
      mime-types: # 可以被压缩的类型
      - text/html
      - application/xml
      - application/json
      min-request-size: 2048   # 超过2048字节进行压缩
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://edmin:mldnjava@eureka-7001.com:7001/eureka